"use client";

import { useState } from "react";
import styles from "./Accordian.module.css";

// Accordian generated by AI

export interface AccordionItem {
  id: string;
  question: string;
  answer: string;
}

interface AccordionProps {
  title?: string;
  items: AccordionItem[];
  /** Allow multiple items open at once. Default: false */
  allowMultiple?: boolean;
}

export default function Accordion({
  title = "Ofte stilte spørsmål",
  items,
  allowMultiple = false,
}: AccordionProps) {
  const [openIds, setOpenIds] = useState<Set<string>>(new Set());

  const toggle = (id: string) => {
    setOpenIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        if (!allowMultiple) next.clear();
        next.add(id);
      }
      return next;
    });
  };

  return (
    <section className={styles.wrapper}>
      {title && <h2 className={styles.title}>{title}</h2>}
      <ul className={styles.list}>
        {items.map((item) => {
          const isOpen = openIds.has(item.id);
          return (
            <li key={item.id} className={styles.item}>
              <button
                className={styles.trigger}
                onClick={() => toggle(item.id)}
                aria-expanded={isOpen}
                aria-controls={`accordion-panel-${item.id}`}
                id={`accordion-btn-${item.id}`}
              >
                <span className={styles.question}>{item.question}</span>
                <ChevronIcon
                  className={`${styles.icon} ${isOpen ? styles.iconOpen : ""}`}
                />
              </button>
              <div
                id={`accordion-panel-${item.id}`}
                role="region"
                aria-labelledby={`accordion-btn-${item.id}`}
                className={`${styles.panel} ${isOpen ? styles.panelOpen : ""}`}
              >
                <p className={styles.answer}>{item.answer}</p>
              </div>
            </li>
          );
        })}
      </ul>
    </section>
  );
}

function ChevronIcon({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      aria-hidden="true"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M5 7.5L10 12.5L15 7.5"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
